import type { Metadata } from "next";
import ScrollReveal from "@/components/scroll-reveal";
import { site } from "@/content/site";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Award, Shield, Clock, CheckCircle2 } from "lucide-react";
import { breadcrumbJsonLd, buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({
  title: "Sobre PROSELEC, S.A.",
  description: "Conoce a PROSELEC, S.A., empresa panameña fundada en 2011 con experiencia en obras civiles, arquitectura e instalaciones electromecánicas.",
  path: "/sobre-nosotros",
  keywords: ["sobre PROSELEC", "empresa electromecánica Panamá", "empresa de obras civiles Panamá", "PROSELEC Santiago Veraguas"],
});

export default function SobreNosotrosPage() {
  const breadcrumbSchema = breadcrumbJsonLd([{ name: "Inicio", item: "https://proselecpanama.com/" }, { name: "Sobre nosotros", item: "https://proselecpanama.com/sobre-nosotros" }]);
  return (
    <div className="bg-white">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <div className="border-b border-slate-200 bg-[radial-gradient(circle_at_20%_10%,rgba(56,189,248,0.14),transparent_55%),radial-gradient(circle_at_80%_20%,rgba(29,78,216,0.12),transparent_55%),linear-gradient(to_bottom,#f8fafc,#ffffff)] pt-24"><div className="mx-auto max-w-6xl px-4 pb-10 sm:px-6"><div className="text-xs font-extrabold text-sky-700">PROSELEC</div><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl">Sobre PROSELEC, S.A.</h1><p className="mt-2 max-w-2xl text-slate-600">Empresa panameña enfocada en obras civiles, arquitectura y soluciones electromecánicas.</p></div></div>
      <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6"><div className="grid gap-6 lg:grid-cols-3"><ScrollReveal><Card className="overflow-hidden rounded-3xl border-slate-200"><div className="h-1.5 w-full bg-gradient-to-r from-sky-600 to-blue-700" /><CardHeader className="pb-2"><CardTitle className="text-base">Quiénes somos</CardTitle><CardDescription>Fundada en {site.founded}</CardDescription></CardHeader><CardContent className="pt-2"><p className="text-sm leading-relaxed text-slate-600">{site.about}</p></CardContent></Card></ScrollReveal><ScrollReveal delay={0.05}><Card className="overflow-hidden rounded-3xl border-slate-200"><div className="h-1.5 w-full bg-gradient-to-r from-sky-600 to-blue-700" /><CardHeader className="pb-2"><CardTitle className="text-base">Misión</CardTitle><CardDescription>Enfoque técnico y calidad</CardDescription></CardHeader><CardContent className="pt-2"><p className="text-sm leading-relaxed text-slate-600">{site.mission}</p></CardContent></Card></ScrollReveal><ScrollReveal delay={0.1}><Card className="overflow-hidden rounded-3xl border-slate-200"><div className="h-1.5 w-full bg-gradient-to-r from-sky-600 to-blue-700" /><CardHeader className="pb-2"><CardTitle className="text-base">Visión</CardTitle><CardDescription>Innovación y vanguardia</CardDescription></CardHeader><CardContent className="pt-2"><p className="text-sm leading-relaxed text-slate-600">{site.vision}</p></CardContent></Card></ScrollReveal></div>
      <ScrollReveal delay={0.15}><div className="mt-10 rounded-3xl border border-slate-200 bg-gradient-to-b from-slate-50 to-white p-7 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-2xl bg-sky-50 p-3 ring-1 ring-sky-100"><Award className="h-5 w-5 text-sky-700" /></div><div><div className="text-lg font-extrabold text-slate-900">¿Por qué elegirnos?</div><div className="text-sm text-slate-600">{site.description}</div></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{ icon: Shield, title: "Calidad", desc: "Servicio enfocado en calidad y cumplimiento técnico." }, { icon: Shield, title: "Seguridad", desc: "Ejecución con enfoque preventivo y estándares de seguridad." }, { icon: Clock, title: "Confiabilidad", desc: "Soluciones consistentes para proyectos reales de obra." }, { icon: Award, title: "Innovación", desc: "Criterio técnico y mejora continua en cada intervención." }].map((b) => <div key={b.title} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-sky-50 ring-1 ring-sky-100"><b.icon className="h-5 w-5 text-sky-700" /></div><div className="font-extrabold text-slate-900">{b.title}</div></div><p className="mt-3 text-sm leading-relaxed text-slate-600">{b.desc}</p></div>)}</div><div className="mt-6 flex items-start gap-2 rounded-2xl border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 text-sky-700" /><p className="text-sm text-slate-600">PROSELEC integra conocimiento técnico, planificación y ejecución para responder a necesidades de obra civil, arquitectura e instalaciones electromecánicas en Panamá.</p></div></div></ScrollReveal></section>
    </div>
  );
}
